.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SLIDER 1 "June 13, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
slider \- Build sound waves from component parts
.SH SYNOPSIS
.B slider
.RI [ file ]
.SH DESCRIPTION
.B slider
is an interactive program designed to help you synthesize sound
effects by building them from harmonics and by combining multiple
combinations of non-harmonic sine waves.

The typical form of invoking Slider is through the desktop
environment.  If called from the command line with one argument,
slider will attempt to open the given file.
.SH AUTHOR
slider was written by Andrew Makousky.
.PP
This manual page was written by Andrew <andrew@liberty-dell>,
for the Debian project (and may be used by others).
